trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:

  - powershell: |
      Get-ChildItem -Path '$(Build.SourcesDirectory)/CustomPackages' -Filter *.mplig |
      Rename-Item -NewName { $_.Name -replace '\.mplig$','.nupkg' }
    displayName: 'Convert to NuGet Packages'

  - powershell: |
      nuget sources add -Name "LocalPackages" -Source "$(Build.SourcesDirectory)/CustomPackages"
    displayName: 'Add Local NuGet Feed'
    env:
      NUGET_EXE: $(Agent.ToolsDirectory)\nuget.exe  # Ensures nuget.exe is available
      
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      includeNuGetOrg: true
      vstsFeed: 'LocalPackages'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'drop'

- deployment: DeployToProduction
  displayName: 'Deploy to Production'
  environment: Production-Windows
  dependsOn: Build
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
          
        - task: IISWebAppDeploymentOnMachineGroup@0
          inputs:
            WebSiteName: 'MyAPI'
            Package: '$(Pipeline.Workspace)/drop/WebApp.zip'
            RemoveAdditionalFilesFlag: true
            TakeAppOfflineFlag: true