trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # Add custom packages path as global environment variable
  NUGET_PACKAGES: '$(Build.SourcesDirectory)/CustomPackages'

jobs:
- job: Build
  steps:
  # STEP 1: Add local folder as NuGet source
  - powershell: |
      # Create temporary NuGet config with local source
      $configContent = @"
      <?xml version="1.0" encoding="utf-8"?>
      <configuration>
        <packageSources>
          <add key="CustomPackages" value="$(Build.SourcesDirectory)/CustomPackages" />
          <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
        </packageSources>
      </configuration>
      "@
      Set-Content -Path "$(Build.SourcesDirectory)/nuget.temp.config" -Value $configContent
    displayName: 'Create temporary NuGet config'

  # STEP 2: Restore with custom config
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)/nuget.temp.config'  # Use custom config
    displayName: 'NuGet restore with custom packages'

  # STEP 3: Build solution
  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  # ... rest of your tasks (test, publish artifacts)

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(build.artifactStagingDirectory)'
      artifactName: 'drop'

- deployment: DeployToProduction
  displayName: 'Deploy to Production'
  environment: Production-Windows
  dependsOn: Build
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
          
        - task: IISWebAppDeploymentOnMachineGroup@0
          inputs:
            WebSiteName: 'MyAPI'
            Package: '$(Pipeline.Workspace)/drop/WebApp.zip'
            RemoveAdditionalFilesFlag: true
            TakeAppOfflineFlag: true
            # ADD THESE PARAMETERS TO TARGET YOUR VM:
            ComputerName: 'your-vm-name'  # Replace with actual VM name
            UserName: 'your-username'     # VM admin username
            Password: 'your-password'     # VM admin password
            WebDeployServiceUrl: 'https://your-vm-ip:8172/msdeploy.axd'  # VM IP/DNS
            AuthType: 'Basic'